# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"[\n\x12InferSchemaRequest\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x0f\n\x07samples\x18\x04 \x03(\t\"\x86\x01\n\x13InferSchemaResponse\x12\x13\n\x0bschema_json\x18\x01 \x01(\t\x12\x12\n\nservice_id\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x14\n\x0csample_count\x18\x05 \x01(\x05\x12\x0e\n\x06\x63\x61\x63hed\x18\x06 \x01(\x08\x32_\n\x0fSchemaInference\x12L\n\x0bInferSchema\x12\x1d.inference.InferSchemaRequest\x1a\x1e.inference.InferSchemaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERSCHEMAREQUEST']._serialized_start=30
  _globals['_INFERSCHEMAREQUEST']._serialized_end=121
  _globals['_INFERSCHEMARESPONSE']._serialized_start=124
  _globals['_INFERSCHEMARESPONSE']._serialized_end=258
  _globals['_SCHEMAINFERENCE']._serialized_start=260
  _globals['_SCHEMAINFERENCE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
